openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing contacts and user authentication.
tags:
  - name: Contacts
    description: Endpoints related to managing contacts.
  - name: Auth
    description: Endpoints related to user authentication and authorization.
servers:
  - url: https://nodejs-hw-mongodb-j6tx.onrender.com
security:
  - bearerAuth: []
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    put:
      $ref: ../swagger/paths/contacts/{id}/put.yaml
  /auth/register:
    post:
      security: []
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/resetPasswordEmail.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/resetPassword.yaml
  /auth/get-oauth-url:
    get:
      $ref: ../swagger/paths/auth/oauth-url.yaml
  /auth/confirm-oauth:
    post:
      $ref: ../swagger/paths/auth/oauth-login.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
